# Generated by Django 4.1.2 on 2022-12-02 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front_page_ip', '0003_city_latitude_city_longitude_country_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ci_state', to='front_page_ip.state'),
        ),
        migrations.AlterField(
            model_name='personlocation',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_state', to='front_page_ip.state'),
        ),
    ]
