# Generated by Django 4.1.2 on 2022-12-02 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front_page_ip', '0004_alter_city_state_alter_personlocation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ci_state', to='front_page_ip.state'),
        ),
    ]
